# Generated by Django 5.0.1 on 2024-01-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='qr_src',
            field=models.URLField(max_length=300),
        ),
    ]
